# Generated by Django 5.1.5 on 2025-02-10 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0003_alter_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GENERAL', 'General'), ('SLEEPER', 'Sleeper'), ('LUXURY', 'Luxury')], max_length=20, unique=True)),
                ('fare_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='num_seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Bus.booking'),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusSeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.PositiveIntegerField()),
                ('booked_seats', models.PositiveIntegerField(default=0)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_seat_classes', to='Bus.bus')),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.seatclass')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Bus.seatclass'),
        ),
        migrations.AddField(
            model_name='bus',
            name='seat_classes',
            field=models.ManyToManyField(through='Bus.BusSeatClass', to='Bus.seatclass'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Bus.seatclass'),
        ),
    ]
