# Generated by Django 5.1.5 on 2025-02-13 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0005_busstop_route_booking_google_id_booking_end_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_stop',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='end_booking', to='Bus.busstop'),
            preserve_default=False,
        ),
    ]
