# Generated by Django 5.1.5 on 2025-02-18 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0007_profile_email_otp_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bus.route'),
        ),
    ]
