# Generated by Django 5.1.5 on 2025-02-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0008_bus_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='num_seats',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='ACCEPTED', max_length=10),
        ),
    ]
